### ISSUE TITLE
PureEntities 가 아닌 PureEntitiesX 로.

### ISSUE THREAD

**Issue by raidksh** [Sagwa-plugins/WardenMonster-PMMP#1]
PureEntitiesX 플러그인의 엔티티 기능은 leinne 의 PureEntities 플러그인 보다 훨씬 뛰어납니다.

PureEntitiesX 를 사용하는 유저를 위해 PureEntitiesX 을 기반으로 제작하여 주세요.

이하, 광물 플러그인도 부탁드립니다.

**Comment by LeinneSW** [comment]
PureEntitiesX는 업데이트가 중단됐습니다:(
+ PureEntities 는 4.0.0 API를 지원합니다
그리고 무엇보다 사과서버 전용 플러그인이지 공유용 플러그인이 아닙니다.

**Comment by raidksh** [comment]
알겠습니다, 그럼 광물, 파수꾼 엔티티는 어떻게 소환하나요?
